baseURL: "https://pav.rs/"
title: Filip Pavlovic | PAV.rs
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Pav.rs
    description: "sysadmin | salesman | cat lover | robot | project manager | IT engineer"
    keywords: [Portfolio]
    author: Filip Pavlovic
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "PAV.rs"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Hi, I'm Filip
        subtitle: "sysadmin - cat lover - robot - project manager - IT engineer"
        imageUrl: "https://lh3.googleusercontent.com/8th5V48c5V-oiUB0SrgcEix1aAKrfZ-2sW1SlWDrGgHCNecPBPcakMa3qE4pLZe4OorhfQS5mG9qMWPoOsXaG7p_wjW0MSMY0m4omjDhdkUqcfH1edDM5tt4NZAe-R7P1dCs-Em7sD-MEN1LM2D98BX6MHW6bslV01eI51Ga9mQ3zHHkc-ui-676XcMRijGG1GOllNm3rOA7NA87GUcqszMS2w-wGiNVAvJ_JMLVjDRemdRfrcc0fBzQYvwlRM1kGmHznF9XijNFcASNno_9JZgrTD6SPPbog8XYsHxiZcPKV9PMCf7deM82km_rS9kYgFYiNGQHPfwUi4fVZ-Fm4eqBhrIGAzTZzWiG-7iLPQ1vGOoJpZVAPaEyXXdlcbBZ0GLty3agi1eD91PACoi5_hoP-gafw7JEfcrKcJ3CB2xobkFZ0VANIsUpjeWCkYIKlBWtbokmxpJb5yWJZTW1CIw7vVbfewUfuMHwUNRr22_BtI6dbPwXNTz9GWuv3SrtoRUB7tnQZgy8IYd6jZ2oLF7h_FlbeWEyG9U_pQ3GQdE7tgRe5MUZLsqyDiv1rSDPbszHWvwdMwSoM8GQ-yZYDK-6uGenTu5u641mAAu965rOc4C3NpcPLHDY6D7gFssxuisXLZRWhUV6fuCnQ51id-ZVthNwYivpX7xPqcyoWOkqE3lCvEY9Ly4niFsi7MQZZLaj-E2MK7lHLHivWlI_4GgCmYunp4tpkDatYZhTWBsoFgkYnQgtL1fg6lQ=w890-h667-no?authuser=0"
        imageWidth: 200
        imageHeight: 150
        imageTitle: Bella
        #buttons:
            #- name: Posts
              #url: posts
            #- name: Tags
              #url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: instagram
          url: "https://instagram.com/filip.pvl"
        - name: facebook
          url: "https://facebook.com/filippvl"
        - name: github
          url: "https://github.com/filippvl"
        - name: email
          url: "mailto:filip@pav.rs"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: resume
          name: Resume
          url: /resume/
          weight: 10
        - identifier: contact
          name: Contact
          url: /contact/
          weight: 20
        - identifier: email
          name: filip@pav.rs
          url: mailto:filip@pav.rs
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
